name: Test

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13, macos-14]

    steps:
    - uses: actions/checkout@v4

    - name: Build tests
      run: |
        cmake test/CMakeLists.txt  -B build
        cmake --build build

    - name: Run tests
      if: matrix.os == 'windows-latest'
      run: |
        .\build\Debug\test.exe

    - name: Run tests
      if: matrix.os != 'windows-latest'
      run: |
        ./build/test